// <auto-generated />
namespace _200423_ExoEntity5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class StatisticsChange20200423N001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StatisticsChange20200423N001));
        
        string IMigrationMetadata.Id
        {
            get { return "202004230843248_StatisticsChange20200423N001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
